In [5]:
#import all modules here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import sklearn.linear_model as sk
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from collections import defaultdict
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from random import randint
from IPython.display import display
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn import preprocessing
import seaborn as sn
from sklearn.preprocessing import StandardScaler
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

In [69]:
N = 14
df = pd.read_csv('SPECT.train',header=None)
features = df.loc[:,df.columns!=0]
label = df[0]

In [7]:
data_df = pd.read_csv("haberman.data",header=None)
data_df.fillna(data_df.median(),inplace=True)
data_df.columns = ['Age','Year','Nodes','Survival_status']
data_df['Survival_status'] = data_df['Survival_status'].astype(int)
data_df['Survival_status'] = data_df['Survival_status'].map({2:0 , 1:1})

In [64]:
def distance_from_centroid(df,centroids,data_label):
    d = defaultdict(list)
    for index in df.index:
        dist = 0
        for i in range(len(centroids[0])):
            dist+=(centroids[df.loc[index,'cluster']][i] - df.loc[index,df.columns[i]])**2
        d[df.loc[index,'cluster']].append([dist,index,data_label[index]])
    return d

In [71]:
def ratio_in_cluster(features,data_label,n):
    km = KMeans(n_clusters = n)
    km.fit(features)
    label = km.labels_
    print(len(label))
    print(features.shape)
    features['cluster'] = label
    
    distance = distance_from_centroid(features,km.cluster_centers_,data_label)
    
    for i in distance.keys():
        distance[i] = sorted(distance[i],key=lambda x: x[0])
        
    normalized_distance = dict(distance)
    label_ratio_count = {}
    for i in normalized_distance:
        temp = [0,0]
        for j in range(len(normalized_distance[i])):
            normalized_distance[i][j][0] = normalized_distance[i][j][0]/normalized_distance[i][-1][0]
            temp[normalized_distance[i][j][-1]] +=1

        temp[0],temp[1] = temp[0]/sum(temp),temp[1]/sum(temp)
        label_ratio_count[i] = temp

    return pd.DataFrame(data=label_ratio_count)

In [72]:
ratio_in_cluster(data_df.loc[:,data_df.columns!='Survival_status'],data_df['Survival_status'],14)

306
(306, 4)

,6,12,9,13,11,3,2,0,8,7,4,10,1,5
0,0.045455,0.125,0.555556,0.333333,0.190476,0.666667,0.631579,0.232558,0.175,0.5,0.178571,0.545455,0.195122,0.222222
1,0.954545,0.875,0.444444,0.666667,0.809524,0.333333,0.368421,0.767442,0.825,0.5,0.821429,0.454545,0.804878,0.777778

In [73]:
ratio_in_cluster(features,label,14)

80
(80, 23)

,2,1,13,7,11,4,0,5,3,6,8,9,10,12
0,0.0,0.333333,0.6,0.5,0.333333,0.2,0.740741,0.0,0.0,0.642857,0.5,0.0,0.0,0.5
1,1.0,0.666667,0.4,0.5,0.666667,0.8,0.259259,1.0,1.0,0.357143,0.5,1.0,1.0,0.5